### ISSUE TITLE
Support for RC and RD in :61: funds_code

### ISSUE THREAD

**Issue by HDGhost** [railslove/cmxl#14]
In MT940 (example here: https://www.kontopruef.de/mt940s.shtml) you need to accept up to two letters in the :61: funds_code

In your code (cmxl/lib/cmxl/fields/transaction.rb) you check for one letter 'C' or 'D', but in case of Storno you get a 'RC' or 'RD' which would cause an error in your cmxl-lib.

Can you fix these issue pls?

Greetings Ghost

**Comment by bumi** [comment]
Hi Ghost, 
thanks for reporting this. As you noted cmxl currently only supports "C" and "D". 
Are you interested in contributing the requested feature? I'd be happy to support you.

**Comment by HDGhost** [comment]
Hi bumi, thx for the fast answer.
I would like to resolve this issue with you, but unfortunately there is no time for doing this atm.
I wrote from work where i have another big project, that needs to be done in a short time.

**Comment by bumi** [comment]
sure, we all know that ant it is the same here... a lot of things to do.
I will keep this issue open for whoever finds time first.
