### ISSUE TITLE
Unencrypted secret in codebase

### ISSUE THREAD

**Issue by leoarnold** [railslove/cmxl#45]
https://github.com/railslove/cmxl/blob/5e41274340922d8e81089d6e0f8a64ba027ee846/.semaphore/semaphore.yml#L20-L21

Worst case is that someone might send differing data to CodeClimate. That aside, it may be annoying if all forks post to the same CodeClimate Project.

**Comment by bumi** [comment]
autsch :) thanks, even though that should be invalid. 

but I'd like to get travis back and remove that semaphore
