### ISSUE TITLE
chore: Enable Semaphore CI runs for tests

### ISSUE THREAD

**Issue by olleolleolle** [railslove/cmxl#47]
Hello!

It seems to me that there are no CI runs connected to commits right now, is that right?

**Comment by bumi** [comment]
thanks, yep. seems CI is currently broken. I will fix this. 

@Uepsilon why did you do #39 and #40 
Can I revert to travis?

**Comment by bumi** [comment]
Travis is back: https://travis-ci.org/github/railslove/cmxl
