### ISSUE TITLE
Parsing issue in field.rb:51- 'Wrong line format'

### ISSUE THREAD

**Issue by kmcital** [railslove/cmxl#8]
Error message:
/Users/xxxx/.rvm/gems/ruby-2.2.1/gems/cmxl-0.1.3/lib/cmxl/field.rb:51:in `parse': Wrong line format: "{1:F01AXISINBBAXXXXXXXXXXXXX}{2:I940XXXXXXXXAXXXN}{4:" (Cmxl::Field::LineFormatError)

Perhaps the statement_separator I'm using doesn't match my file:

`Cmxl.config[:statement_separator] = /\n-.\n/m`

Here is the MT940 file I'm trying to parse and convert:

```
{1:F01AXISINBBAXXXXXXXXXXXXX}{2:I940XXXXXXXXAXXXN}{4:
:20:MT940/78274
:25:xxxxxxxxxxxxxx
:28C:3/1
:60F:C160201INR0,00
:61:1602080208CR1338474,92NMSC89962273
:86:-TX BRN-REF NO.0234FIR1600187 USD 19995/RLZ           
:61:1602120212DR390000,00NCHK73401
:86:-CHQ73401   TX BRN-CLG-CHQ PAID TO SANTHANA                      
:61:1603050305DR27300,00NCHK73403
:86:-CHQ73403   TX BRN-CLG-CHQ PAID TO SANTHANA                      
:61:1604060406DR39000,00NCHK73404
:86:-CHQ73404   TX BRN-CLG-CHQ PAID TO SANTHANA                      
:61:1604150415DR33249,00NCHK73405
:86:-CHQ73405   TX BRN-CLG-CHQ PAID TO CHENNAI AIRCONDITIONERS       
:61:1604280428DR5000,00NCHK73406
:86:-CHQ73406   TX VERVE FINANCIAL SERVICES PVT LTD                  
:61:1604300430DR392751,00NCHK73407
:86:-CHQ73407   TX BY SALARY                                         
:61:1605040504DR35100,00NCHK73408
:86:-CHQ73408   TX BRN-CLG-CHQ PAID TO P SANTHANA GOPALA KRISHNA     
:61:1605070507DR5000,00NCHK73402
:86:-CHQ73402   TX BRN-CLG-CHQ PAID TO RELIANCE COMMUNICATI          
:61:1605090509DR76917,00NMSC315222
:86:-TX INB/NEFT/AXIR161301965349/Reliance Comm/Reliance B
:61:1605120512CR1322831,02NMSC96582848
:86:-TX BRN-REF NO.0234FIR1600665 USD 19995/RLZ           
:61:1605170517DR61425,00NTRF7335278
:86:-TX INB/IFT/ANITHA SURESH/Admin Reimbursement         
:61:1605250525DR38000,00NCHK73409
:86:-CHQ73409   TX VERVE FINANCIAL SERVICES                          
:62F:C160527INR1557563,94
-}
```

**Comment by bumi** [comment]
those `{` are part of the your MT940 file?
can you parse it from the `:20:` to the `:62F:` ? 

Everytime I look at a MT940 file I have to relearn the structure :) - what an human-unfriendly format :)

**Comment by kmcital** [comment]
Agreed, it's not a friendly format.  Yes, what I pasted above is the entire file. Starts with `{1:xxx}` which is the bank identifier, then `{2:I940xxx}` some other identifier, and then the statement record in the `{4: ... }`.

So I created a test file with contents just from `:20:` to `:62F:` lines and got this:

```
MT940/78274

0.0
1557563.94

convert.rb:18:in `block in <main>': undefined method `sha' for nil:NilClass (NoMethodError)
	from convert.rb:13:in `each'
	from convert.rb:13:in `<main>'
```

**Comment by bumi** [comment]
is `convert.rb` your file? (I think it is not part of the gem) what is line 18 doing?

**Comment by bumi** [comment]
the `{1:` looks somehow "invalid" (nothing is invalid in MT940) to me as I thought the field identifiers start with `:` as for example in this file: https://github.com/railslove/cmxl/blob/master/spec/fixtures/mt940-deutsche_bank.txt

**Comment by kmcital** [comment]
Yes, `convert.rb` is my program, here it is in it's entirety (line 18 is `puts.sha`):

```
require 'cmxl'

# Configuration:
# Cmxl currently allows you to configure the statement divider - though the default should be good in most of the cases
# and you can configure if line parsing errors should be raised

Cmxl.config[:statement_separator] = /\n-.\n/m
Cmxl.config[:raise_line_format_errors] = true

# Statment parsing:

statements = Cmxl.parse(File.read('mt940_test.txt')) # parses the file and returns an array of statement objects. Please note: if no encoding is given Cmxl tries to guess the encoding from the content and converts it to UTF-8. 
statements.each do |s|
  puts s.reference
  puts s.generation_date
  puts s.opening_balance.amount
  puts s.closing_balance.amount
  puts.sha # SHA of the statement source - could be used as an unique identifier

  s.transactions.each do |t|
    puts t.information
    puts t.description
    puts t.entry_date
    puts t.funds_code
    puts t.credit?
    puts t.debit?
    puts t.sign # -1 if it's a debit; 1 if it's a credit
    puts t.name
    puts t.iban
    puts t.sepa
    puts t.sub_fields
    puts t.reference
    puts t.bank_reference
    # ...
  end
end
```

**Comment by bumi** [comment]
line 18 is an error in your program. it should look like: 
`puts s.sha` - similar to the lines above.

(`puts` is a method that returns nil so `puts.sha` is equal to `puts().sha` and calling the `sha` method on `nil` which is obviously not defined there.)

**Comment by kmcital** [comment]
Sorry - didn't catch that, I copied this program from the READ.ME and must have not pasted correctly into my program. So it is parsing correctly now, just the transactions themselves.  Those `{` come from the format of SWIFT MT940 our bank is using which is consistent with this documentation I found:

http://martin.hinner.info/bankconvert/swift_mt940_942.pdf

**Comment by bumi** [comment]
ah true, swift header... Which bank are you using? 
I guess those are currently not supported by CMXL but it should be easy to add those. - if you want to send a PR? 

But do you need that information? you could also just strip it before parsing the statement with CMLX.

**Comment by kmcital** [comment]
Axis Bank in India.  And no, we don't need that information so I'll just strip it before parsing, no worries!

Thanks so much for your quick replies on this today!! Very helpful.

**Comment by bumi** [comment]
ok, happy to hear that it works for you. And as far as I know that is the first bank in India. great! 
I've created an issue for the SWIFT headers: #9
